version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: nest_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: B2k25ismine@1$
      POSTGRES_DB: jwt-auth
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: nest_redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:
